import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import Link from "next/link"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <nav className="max-w-3xl mx-auto px-6 py-4 flex gap-4 text-sm text-gray-600 border-b border-gray-200">
          <Link href="/" className="hover:text-black">
            Dashboard
          </Link>
          <Link href="/applications" className="hover:text-black">
            Applications
          </Link>
          <Link href="/board" className="hover:text-black">
            Board
          </Link>
          <Link href="/criteria" className="hover:text-black">
            Criteria
          </Link>
          <Link href="/feed" className="hover:text-black">
            Vacancies
          </Link>
        </nav>
      </body>
    </html>
  )
}
